environment:

  matrix:

    - PYTHON: "34"
    
image: Visual Studio 2015

platform:
  - x64

install:
  - echo CALL "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - "C:\\Python%PYTHON%-x64\\python.exe -m pip install scandir==1.5"

build: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
