environment:


    - PYTHON: "27"

    - PYTHON: "34"

    - PYTHON: "35"
    
    - PYTHON: "36"
    

platform:
  - x86

install:
  - "C:\\Python%PYTHON%-x64\\python.exe -m pip install scandir==1.5"

build: off
